Book model
wolox-training/jr-rails pull request #6
Opened 2018-09-07 17:04 UTC by juanpablo-rojas

2018-09-10 12:34 UTC, MatiasComercio requested changes

2018-09-10 12:34 UTC, MatiasComercio commented on app/models/book.rb
> +  validates :genre, presence: true # Make field required
Comment is not necessary as this line says that explicitly.

2018-09-10 12:34 UTC, MatiasComercio commented on app/models/book.rb
> +  validates :genre, presence: true # Make field required
Same for all the lines below.

2018-09-10 12:34 UTC, MatiasComercio commented on db/migrate/20180906225330_create_books.rb
> +      t.string :genre, null: false, default: ""
`default` should not be here, as not specifying any value for model creation will lead to this default, which is indeed a valid not null string, i.e., this `default` is bypassing the `null: false` validation in some way.
You can check this by running `Book.new` (without any arguments) in your rails console.

2018-09-10 12:34 UTC, MatiasComercio commented on db/migrate/20180906225330_create_books.rb
> +      t.string :genre, null: false, default: ""
Same for all the lines below.

2018-09-10 12:44 UTC, MatiasComercio commented
I see through all these last commits that titles are so long that they can be visualized in a single line.
Long commit titles are not ok, and long does not mean descriptive.
A good post for conventions you may read and put in practice since now is [this one](https://chris.beams.io/posts/git-commit/).

There is no convention in Wolox for the following, but at least this is what I find better for my every day work: I love squashing and rebasing. You should use those two tools with caution (and know when merging would be a better choice), but once you master them, git history is so much cleaner and readable that you will be pleased of learning to use them. Let me know if you want to start learning to use them (only if @hdf1986 agrees of course).

2018-09-10 19:28 UTC, hdf1996 requested changes

2018-09-10 19:28 UTC, hdf1986 commented on app/models/book.rb
> +  validates :genre, presence: true
We tend to prefer the oneliner version of this when possible. Something like:
```
validates :genre, :author, :image,..., presence: true
```

2018-09-11 12:27 UTC, MatiasComercio approved these changes

2018-09-11 12:28 UTC, MatiasComercio commented
**PLEASE** wait for @hdf1986 approval. Also, don't forget to read the suggested post for git commits conventions (read my previous comment).

2018-09-12 12:48 UTC, hdf1996 approved these changes

2018-09-12 13:39 UTC, merged